FROM node:22
RUN apt-get update \
&& apt-get install -y git
RUN git config --global --add safe.directory /app
RUN git config --global user.name "lucasstandre"
RUN git config --global user.email "lucas.st.andre@gmail.com"
