name: my first pipeline
on:
  push:
jobs:
  bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Dire bonjour
        run: echo "Je suis le job bonjour"

  aurevoir:
    runs-on: ubuntu-latest
needs: bonjo # attends que le job bonjour soit termine
    steps:
      - name: Dire aurevoir
      run: echo "Je suis le job aurevoir, bonjour est terminé"
