name: Mon premier pipeline
on:
  push:

jobs:
  bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Dire bonjour
        run: echo "Je suis le job bonjour"
      - name: Une étape qui échoue
        run: exit 1
      - name: Cette étape ne s'exécutera pas
        run: echo "on ne me verra jamais"
