name: CI Laravel

on: # déclencheurs
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  tests: # nom du job
    runs-on: ubuntu-latest # runner GitHub-hosted
    steps:
      - name: Checkout du code # clone le dépôt
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, mbstring, bcmath
          coverage: xdebug

      - name: Installer les dépendances
        run: composer install --no-interaction --prefer-dist

      - name: Préparer le .env de test
        run: |
          cp .env.example .env.testing
          php artisan key:generate --env=testing

      - name: Lancer les tests
        run: php artisan test

